FROM node:10-alpine as builder
WORKDIR /usr/src/app
COPY package*.json /app
RUN npm install

FROM node:10-alpine as delivery
ENV PATH /app/node_modules/.bin:$PATH
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/node_modules /usr/src/app/node_modules
COPY . .
CMD [ "node", "server.js" ]
